// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.tsx";
import * as $_platform_characters_id_ from "./routes/(platform)/characters/[id].tsx";
import * as $_platform_characters_middleware from "./routes/(platform)/characters/_middleware.tsx";
import * as $_platform_characters_house_house_ from "./routes/(platform)/characters/house/[house].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $characters from "./routes/characters.tsx";
import * as $favorites from "./routes/favorites.tsx";
import * as $favorites_add from "./routes/favorites/add.tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $students from "./routes/students.tsx";
import * as $Login from "./islands/Login.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.tsx": $_platform_middleware,
    "./routes/(platform)/characters/[id].tsx": $_platform_characters_id_,
    "./routes/(platform)/characters/_middleware.tsx":
      $_platform_characters_middleware,
    "./routes/(platform)/characters/house/[house].tsx":
      $_platform_characters_house_house_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/characters.tsx": $characters,
    "./routes/favorites.tsx": $favorites,
    "./routes/favorites/add.tsx": $favorites_add,
    "./routes/index.tsx": $index,
    "./routes/logout.tsx": $logout,
    "./routes/students.tsx": $students,
  },
  islands: {
    "./islands/Login.tsx": $Login,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
